apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.5.3"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    replicaCount: 2